### ISSUE TITLE
Implement QDMI_control_test

### ISSUE THREAD

**Issue by flowerthrower** [Munich-Quantum-Software-Stack/MQSS-QDMI-Devices-Suite#2]
https://github.com/Munich-Quantum-Software-Stack/backends/blob/8d32608f01047686ee74fc719e8f0fafc0e612f4/src/ibm.c#L34

When I try to use `QDMI_control_wait`, I get an error because `QDMI_control_test` is not implemented.
@Durganshu could you kindly look into this?

**Comment by Durganshu** [comment]
Hi @flowerthrower 

Please review the changes here: https://github.com/Munich-Quantum-Software-Stack/backends/pull/4. 

I hope this works for your testing.
