### ISSUE TITLE
Exporting targets for the repository

### ISSUE THREAD

**Issue by Durganshu** [Munich-Quantum-Software-Stack/MQSS-QDMI-Devices-Suite#9]
The `backends` repo should also export its targets (as QDMI does).

Like here: 
https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/b966745af7187994496ec99d89b4426cea62e96a/CMakeLists.txt#L51-L75

This will help in using the backends in other projects

**Comment by burgholzer** [comment]
Fully agree. In fact, the CMake configuration of this project should be refactored as a whole to follow common best practices.
I started to do that over in the QInfo repo. Might be worth taking a look there.

**Comment by Durganshu** [comment]
Thanks!
